train:
  seed: 1234
  epochs: 50
  batch_size: 4
  save_every_n_epoch: 1
  precision: 16-mixed
  gradient_clip: 1.0
  if_save_latest: true
  if_save_every_weights: false
  half_weights_save_dir: /Users/kaede/tts/tai_voice_prepared/s1_ckpt
  exp_name: s1_tai

data:
  max_eval_sample: 8
  max_sec: 54
  num_workers: 2
  pad_val: 1024 # same with EOS in model

model:
  vocab_size: 1025
  phoneme_vocab_size: 512
  embedding_dim: 512
  hidden_dim: 512
  head: 16
  linear_units: 2048
  n_layer: 12
  dropout: 0
  EOS: 1024
  random_bert: 0

output_dir: /Users/kaede/tts/tai_voice_prepared/s1_logs

train_semantic_path: /Users/kaede/tts/tai_voice_prepared/6-name2semantic-0.tsv
train_phoneme_path: /Users/kaede/tts/tai_voice_prepared/2-name2text.txt

inference:
  top_k: 5
